# Generated by Django 5.0.1 on 2024-02-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlpauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.TextField(null=True),
        ),
    ]
