# Generated by Django 5.0.1 on 2024-02-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlpauth', '0002_user_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dateOfBirth',
            field=models.TextField(null=True),
        ),
    ]
